version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: "websitedata"
  MYSQL_USER: "MYSQL_USER"
  MYSQL_PASSWORD: "MYSQL_PASSWORD"

services:
  mysql_db:
    image: mysql:8.0.33
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./dbinit:/docker-entrypoint-initdb.d/:ro"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD"
      MYSQL_ROOT_HOST: '%'

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "4001:3001"
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - media:/home/node/app/public/images
      - /app/node_modules
      - ./client:/app
    
  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db

volumes:
  media:        

